import { GetStaticPaths, GetStaticProps } from 'next'
import Head from 'next/head'
import { fetchPhotoInfo } from '~/features/album/client/fetchPhotoInfo'
import { PhotoDetail } from '~/features/album/components/PhotoDetail'
import styles from '~/features/album/styles/PhotolPage.module.css'
import { PhotoDetail as PhotoDetailType } from '~/features/album/types/PhotoDetail'

type Props = {
  data: PhotoDetailType
}

export const PhotoPage = ({ data }: Props) => {
  return (
    <>
      <Head>
        <title>{data.title} | Awesome Album App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.heading}>Awesome Album App</h1>
        <PhotoDetail data={data} />
      </main>
    </>
  )
}
export default PhotoPage

export const getStaticPaths: GetStaticPaths<{ slug: string; id: string }> = async (context) => {
  return {
    paths: [],
    fallback: 'blocking',
  }
}

export const getStaticProps: GetStaticProps<Props, { slug: string; id: string }> = async (context) => {
  const slug = context.params!.slug
  const id = context.params!.id

  const data = await fetchPhotoInfo(slug, id)
  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: {
      data,
    },
    revalidate: 60,
  }
}
