import Head from 'next/head'
import Link from 'next/link'
import { playlistId } from '~/features/config/config'
import styles from '~/features/top/pages/TopPage.module.css'

const TopPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>トップページ</h1>
        <Link href={`/playlist/${playlistId}`}>playlist</Link>
      </main>
    </>
  )
}
export default TopPage
