import { Suspense } from 'react'
import Head from 'next/head'
import { AlbumGrid } from '~/features/album/components/AlbumGrid'
import styles from '~/features/top/pages/TopPage.module.css'

const TopPage = () => {
  return (
    <>
      <Head>
        <title>Awesome Album App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Awesome Album App</h1>
        <Suspense fallback={'loading'}>
          <AlbumGrid />
        </Suspense>
      </main>
    </>
  )
}
export default TopPage
